name: Mineflow
main: aieuo\mineflow\Main
version: 1.3.0
api: 3.13.0
mcpe-protocol:
  - 389
  - 390
  - 407
  - 408
  - 419
  - 422
  - 428
load: POSTWORLD
softdepend:
  - EconomyAPI
  - MoneySystem
  - PocketMoney
  - if
author: aieuo
permissions:
  mineflow.command.mineflow:
    default: op
    description: "mineflow.command.mineflow"
  mineflow.customcommand.op:
    default: op
    description: "mineflow.customcommand.op"
  mineflow.customcommand.true:
    default: true
    description: "mineflow.customcommand.true"
